Repository GSG-G13/Momen-Abdullah-Basel-Konnectify, pull requests merged in 2023-04, with the labels that each got.

#7 add html css files
  public/css/style.css
  public/home.html
  public/index.html
  public/profile.html
  public/userNotFound.html
Labels: done, wating

#10 code app.js and index.js
  src/app.js
  src/index.js
Labels: wating

#13 creat database files and controllers
  src/controllers/handlers.js
  src/controllers/index.js
  src/database/config/build.sql
  src/database/config/connection.js
  src/database/queries/addPostQuery.js
  src/database/queries/getAllPostsQuery.js
  src/database/queries/getUser.js
  src/database/queries/index.js
Labels: wating

#17 Edit front
  package.json
  public/css/signup.css
  public/signup.html
Labels: done

#23 20 do signupp page
  package-lock.json
  public/css/signup.css
  public/js/signup.js
  public/signup.html
  src/controllers/handlers.js
  src/controllers/index.js
  src/database/queries/addUserQuery.js
  src/database/queries/index.js
Labels: done

#27 Posts validation
  package-lock.json
  package.json
  src/utils/validation/index.js
  src/utils/validation/postSchema.js
Labels: done

#28 handle sign in
  package-lock.json
  package.json
  public/js/signup.js
  public/signup.html
  src/controllers/handlers.js
  src/controllers/index.js
  src/database/config/build.sql
  src/database/queries/addUserQuery.js
  src/database/queries/getUser.js
Labels: done

#31 Done the uploud user image
  package-lock.json
  package.json
  public/js/signup.js
  public/signup.html
  public/uploads/1681329603991-155201015-ssssss.jpg
  src/controllers/handlers.js
Labels: done

#35 show all posts
  public/home.html
  public/index.html
  public/js/addPost.js
  public/js/fetchUserData.js
  public/js/getAllPosts.js
  public/js/getLogedUserData.js
  public/js/login.js
  public/js/signup.js
  public/profile.html
  public/uploads/1681336550019-716872406-gaming.jpg
  public/uploads/1681336550020-809467058-gaming.jpg
  public/uploads/1681336556184-483974339-gaming.jpg
  public/uploads/1681336556185-344143262-gaming.jpg
  public/uploads/1681336569398-26673337-gaming.jpg
  public/uploads/1681336569399-730574684-gaming.jpg
  public/uploads/1681336569943-674668287-gaming.jpg
  public/uploads/1681336569943-867038295-gaming.jpg
  public/uploads/1681336719498-505523102-gaming.jpg
  public/uploads/1681336719498-880510522-gaming.jpg
  public/uploads/1681336784087-887436093-gaming.jpg
  public/uploads/1681336784088-462915475-gaming.jpg
  public/uploads/1681336909551-839556155-gaming.jpg
  public/uploads/1681336909551-889702845-gaming.jpg
  public/uploads/1681337622763-246629643-gaming.jpg
  public/uploads/1681337622764-308347664-gaming.jpg
  public/uploads/1681339565360-395789220-gaming.jpg
  public/uploads/1681339565360-466718137-gaming.jpg
  public/uploads/1681341443072-910918874-photo.jpg
  public/uploads/1681341443073-366020942-cv.png
  public/uploads/1681342095364-456993878-gaming.jpg
  public/uploads/1681342095364-633003773-gaming.jpg
  public/uploads/1681342238169-274716238-gaming.jpg
  public/uploads/1681342238170-863887859-gaming.jpg
  src/controllers/handlers.js
  src/controllers/index.js
  src/database/config/build.sql
  src/database/queries/addPostQuery.js
  src/database/queries/addUserQuery.js
  src/database/queries/getUserByName.js
  src/database/queries/index.js
Labels: wating

#36 edite
  public/uploads/1681329603991-155201015-ssssss.jpg
  public/uploads/1681336550019-716872406-gaming.jpg
  public/uploads/1681336550020-809467058-gaming.jpg
  public/uploads/1681336556184-483974339-gaming.jpg
  public/uploads/1681336556185-344143262-gaming.jpg
  public/uploads/1681336569398-26673337-gaming.jpg
  public/uploads/1681336569399-730574684-gaming.jpg
  public/uploads/1681336569943-674668287-gaming.jpg
  public/uploads/1681336569943-867038295-gaming.jpg
  public/uploads/1681336719498-505523102-gaming.jpg
  public/uploads/1681336719498-880510522-gaming.jpg
  public/uploads/1681336784087-887436093-gaming.jpg
  public/uploads/1681336784088-462915475-gaming.jpg
  public/uploads/1681336909551-839556155-gaming.jpg
  public/uploads/1681336909551-889702845-gaming.jpg
  public/uploads/1681337622763-246629643-gaming.jpg
  public/uploads/1681337622764-308347664-gaming.jpg
  public/uploads/1681339565360-395789220-gaming.jpg
  public/uploads/1681339565360-466718137-gaming.jpg
  public/uploads/1681341443072-910918874-photo.jpg
  public/uploads/1681341443073-366020942-cv.png
  public/uploads/1681342095364-456993878-gaming.jpg
  public/uploads/1681342095364-633003773-gaming.jpg
  public/uploads/1681342238169-274716238-gaming.jpg
  public/uploads/1681342238170-863887859-gaming.jpg
Labels: wating

#37 Some editing
  public/index.html
  src/controllers/handlers.js
Labels: done
